packages:
  - packages/*
  - packages/shared/*
  - packages/extensions/*
  - '!**/test/**'

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - esbuild
  - svelte-preprocess

overrides:
  '@types/ws': 8.5.4
  depd: latest
  diff@<4.0.4: '>=4.0.4'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  json5: latest
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  micromatch: latest
  minimatch: latest
  node-abi: latest
  postcss: latest
  semver: latest
  tmp@<=0.2.3: '>=0.2.4'
  ws>bufferutil: '-'
  ws>utf-8-validate: '-'

publicHoistPattern:
  - '*eslint*'
# minimumReleaseAge: 480
# minimumReleaseAgeExclude:
#   - typescript
#   - undici
#   - message2call
#   - better-sqlite3
#   - '@types/node'
#   - svelte
#   - svelte-check
#   - svelte-eslint-parser
#   - svelte-preprocess
#   - '@sveltejs/vite-plugin-svelte'
#   - eslint-plugin-svelte
#   - electron
#   - electron-builder
#   - electron-updater
#   - electron-to-chromium
#   - prettier-plugin-organize-imports
#   - npm-check-updates
