packages:
  - packages/*
  - packages/shared/*
  - packages/extensions/*
  - '!**/test/**'

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - svelte-preprocess

overrides:
  '@types/ws': 8.5.4
  braces@<3.0.3: '>=3.0.3'
  micromatch@<4.0.8: '>=4.0.8'
  depd: 2.0.0
  node-abi: latest
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  ws>bufferutil: '-'
  ws>utf-8-validate: '-'

publicHoistPattern:
  - '*eslint*'
# minimumReleaseAge: 480
# minimumReleaseAgeExclude:
#   - typescript
#   - undici
#   - message2call
#   - better-sqlite3
#   - '@types/node'
#   - svelte
#   - svelte-check
#   - svelte-eslint-parser
#   - svelte-preprocess
#   - '@sveltejs/vite-plugin-svelte'
#   - eslint-plugin-svelte
#   - electron
#   - electron-builder
#   - electron-updater
#   - electron-to-chromium
#   - npm-check-updates
